version: '3'
services:
    db:
        image: mysql:latest
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=flashbox
            - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
        ports:
            - '3306:3306'

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8001:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: mauFJcuf5dhRMQrjj
volumes:
    db:
        driver: local
